package gui.views;

import gui.models.LoaiMonAn.LoaiMonAnModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LeAnhQuan
 */
public class QuanLyLoaiMonAn_GUI extends javax.swing.JFrame {
    
    /**
     * Creates new form QuanLyLoaiMonAn
     */
    
    public QuanLyLoaiMonAn_GUI() {
        initComponents();
    }
    
    public void loadTableLoaiMonAn(ArrayList<LoaiMonAnModel> listLoaiMonAnModel){        
        String col[] = {"ID", "Tên loại món ăn"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        tblLoaiMonAn.setModel(tableModel);
        for(LoaiMonAnModel row : listLoaiMonAnModel){
            Object[] data = {row.getId(), row.getTen()};
            tableModel.addRow(data);
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenLoaiMonAn = new javax.swing.JTextField();
        btnThemLoaiMonAn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiMonAn = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý loại món ăn");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm loại món ăn mới"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Tên loại món ăn");
        jLabel1.setMaximumSize(new java.awt.Dimension(86, 24));
        jLabel1.setMinimumSize(new java.awt.Dimension(86, 24));
        jLabel1.setPreferredSize(new java.awt.Dimension(86, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtTenLoaiMonAn.setMinimumSize(new java.awt.Dimension(64, 24));
        txtTenLoaiMonAn.setPreferredSize(new java.awt.Dimension(200, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel1.add(txtTenLoaiMonAn, gridBagConstraints);

        btnThemLoaiMonAn.setText("Thêm");
        btnThemLoaiMonAn.setMaximumSize(new java.awt.Dimension(72, 24));
        btnThemLoaiMonAn.setMinimumSize(new java.awt.Dimension(72, 24));
        btnThemLoaiMonAn.setPreferredSize(new java.awt.Dimension(72, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        jPanel1.add(btnThemLoaiMonAn, gridBagConstraints);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách loại món ăn"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 50));

        tblLoaiMonAn.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblLoaiMonAn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 381;
        gridBagConstraints.ipady = 322;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        btnXoa.setText("Xóa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 8, 20);
        jPanel2.add(btnXoa, gridBagConstraints);

        getContentPane().add(jPanel2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnThemLoaiMonAn;
    public javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblLoaiMonAn;
    public javax.swing.JTextField txtTenLoaiMonAn;
    // End of variables declaration//GEN-END:variables
}
