/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.views;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author tuant
 */
public class QuanLyQuyen_GUI extends javax.swing.JFrame {
    
    public QuanLyQuyen_GUI() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlThemQuyenMoi = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblChucNang = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        chkQuanLyPhucVu = new javax.swing.JCheckBox();
        chkQuanLyBan = new javax.swing.JCheckBox();
        chkQuanLyMonAn = new javax.swing.JCheckBox();
        chkQuanLyHoaDon = new javax.swing.JCheckBox();
        chkQuanLyNhanVien = new javax.swing.JCheckBox();
        chkQuanLyKhachHang = new javax.swing.JCheckBox();
        chkQuanLyTaiKhoan = new javax.swing.JCheckBox();
        chkBaoCaoThongKe = new javax.swing.JCheckBox();
        lblID1 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblID2 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý quyền");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlThemQuyenMoi.setMinimumSize(new java.awt.Dimension(320, 400));
        pnlThemQuyenMoi.setPreferredSize(new java.awt.Dimension(320, 400));
        pnlThemQuyenMoi.setLayout(new java.awt.GridBagLayout());

        lblID.setText("Mã nhân viên");
        lblID.setMaximumSize(new java.awt.Dimension(100, 16));
        lblID.setMinimumSize(new java.awt.Dimension(100, 16));
        lblID.setPreferredSize(new java.awt.Dimension(100, 16));
        pnlThemQuyenMoi.add(lblID, new java.awt.GridBagConstraints());

        lblChucNang.setText("Chức năng");
        lblChucNang.setMaximumSize(new java.awt.Dimension(60, 16));
        lblChucNang.setMinimumSize(new java.awt.Dimension(60, 16));
        lblChucNang.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        pnlThemQuyenMoi.add(lblChucNang, gridBagConstraints);

        txtMa.setEnabled(false);
        txtMa.setMaximumSize(new java.awt.Dimension(172, 24));
        txtMa.setMinimumSize(new java.awt.Dimension(172, 24));
        txtMa.setPreferredSize(new java.awt.Dimension(172, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 22, 5, 0);
        pnlThemQuyenMoi.add(txtMa, gridBagConstraints);

        btnReset.setText("Reset");
        btnReset.setMaximumSize(new java.awt.Dimension(80, 24));
        btnReset.setMinimumSize(new java.awt.Dimension(80, 24));
        btnReset.setPreferredSize(new java.awt.Dimension(80, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 12);
        pnlThemQuyenMoi.add(btnReset, gridBagConstraints);

        btnSave.setText("Lưu");
        btnSave.setMaximumSize(new java.awt.Dimension(80, 24));
        btnSave.setMinimumSize(new java.awt.Dimension(80, 24));
        btnSave.setPreferredSize(new java.awt.Dimension(80, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 12);
        pnlThemQuyenMoi.add(btnSave, gridBagConstraints);

        chkQuanLyPhucVu.setText("Quản lý phục vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyPhucVu, gridBagConstraints);

        chkQuanLyBan.setText("Quản lý bàn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyBan, gridBagConstraints);

        chkQuanLyMonAn.setText("Quản lý món ăn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyMonAn, gridBagConstraints);

        chkQuanLyHoaDon.setText("Quản lý hoá đơn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyHoaDon, gridBagConstraints);

        chkQuanLyNhanVien.setText("Quản lý nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyNhanVien, gridBagConstraints);

        chkQuanLyKhachHang.setText("Quản lý khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyKhachHang, gridBagConstraints);

        chkQuanLyTaiKhoan.setText("Quản lý tài khoản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyTaiKhoan, gridBagConstraints);

        chkBaoCaoThongKe.setText("Báo cáo thống kê");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkBaoCaoThongKe, gridBagConstraints);

        lblID1.setText("Tên nhân viên");
        lblID1.setMaximumSize(new java.awt.Dimension(100, 16));
        lblID1.setMinimumSize(new java.awt.Dimension(100, 16));
        lblID1.setPreferredSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlThemQuyenMoi.add(lblID1, gridBagConstraints);

        txtTen.setEnabled(false);
        txtTen.setMaximumSize(new java.awt.Dimension(172, 24));
        txtTen.setMinimumSize(new java.awt.Dimension(172, 24));
        txtTen.setPreferredSize(new java.awt.Dimension(172, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 22, 5, 0);
        pnlThemQuyenMoi.add(txtTen, gridBagConstraints);

        lblID2.setText("Chức vụ");
        lblID2.setMaximumSize(new java.awt.Dimension(100, 16));
        lblID2.setMinimumSize(new java.awt.Dimension(100, 16));
        lblID2.setPreferredSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlThemQuyenMoi.add(lblID2, gridBagConstraints);

        txtChucVu.setEnabled(false);
        txtChucVu.setMaximumSize(new java.awt.Dimension(172, 24));
        txtChucVu.setMinimumSize(new java.awt.Dimension(172, 24));
        txtChucVu.setPreferredSize(new java.awt.Dimension(172, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 22, 5, 0);
        pnlThemQuyenMoi.add(txtChucVu, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(pnlThemQuyenMoi, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnReset;
    public javax.swing.JButton btnSave;
    public javax.swing.JCheckBox chkBaoCaoThongKe;
    public javax.swing.JCheckBox chkQuanLyBan;
    public javax.swing.JCheckBox chkQuanLyHoaDon;
    public javax.swing.JCheckBox chkQuanLyKhachHang;
    public javax.swing.JCheckBox chkQuanLyMonAn;
    public javax.swing.JCheckBox chkQuanLyNhanVien;
    public javax.swing.JCheckBox chkQuanLyPhucVu;
    public javax.swing.JCheckBox chkQuanLyTaiKhoan;
    private javax.swing.JLabel lblChucNang;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblID2;
    private javax.swing.JPanel pnlThemQuyenMoi;
    public javax.swing.JTextField txtChucVu;
    public javax.swing.JTextField txtMa;
    public javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
